version: '3'

services:
  db:
    networks:
      alt-web-network:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alt-web-db
    ports:
      - "3306:3306"
    container_name: alt-web-db
    restart: unless-stopped

  server:
    networks:
      alt-web-network:
    image: domengabrovsek/alt-web:server
    ports: 
      - "3000:3000"
    depends_on:
      - db
    # wait 30s for db container to start and start listening on specified port then start server
    command: bash -c "./app/wait-for-it.sh alt-web-db:3306 -t 30 && node ./app/server/index" 
    container_name: alt-web-server
    restart: unless-stopped

networks:
  alt-web-network:
    driver: bridge
