version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alt-web-db
    ports:
      - "3306:3306"
  server:
    image: domengabrovsek/alt-web:server
    ports: 
      - "3000:3000"
  client:
    image: domengabrovsek/alt-web:client
    ports:
      - "8080:8080"