version: '3'

services:

  db:
    networks:
      alt-web-network:
    container_name: alt_web_db
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
      MSSQL_PID: EXPRESS
    restart: unless-stopped

  # app:
  #   networks:
  #     alt-web-network:
  #   image: domengabrovsek/alt-web:app
  #   ports: 
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   # wait 30s for db container to start and start listening on specified port then start server
  #   command: bash -c "./app/wait-for-it.sh alt-web-db:3306 -t 30 && node ./app/server/index" 
  #   container_name: alt-web-app
  #   restart: unless-stopped

networks:
  alt-web-network:
    driver: bridge
